// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukjaqyxpzzvquqzgmtin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVramFxeXhwenp2cXVxemdtdGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzQyNDksImV4cCI6MjA3MTIxMDI0OX0.rvdKpUOPHF3jDvrRQTFqhfGKHr1ogO3fGGAq80cCsIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});